version: '2.1'

services:
 transmission:
    image: linuxserver/transmission
    container_name: transmission
    devices:
        - "/dev/net/tun"
    cap_add:
        - NET_ADMIN
    env_file:
        - stack.env
    volumes:
        # - <path to watch folder>:/watch
        - /media/${USER}/Data/downloads:/downloads
        - /media/${USER}/Data/appdata/transmission:/config
    ports:
        - 9091:9091
        - 51414:51413
        - 51414:51413/udp
        - 8888:8888
        - 8989:8989       # sonarr
        - 9117:9117       # jackett
        - 8686:8686       # lidarr
        - 8083:8083       # calibre-web
        - 8080:8080       # calibre
        - 8082:8081       # calibre 8081 conflict with npm react
        - 7880:7878       # radarr 7878 used by SOAP
        #- 32400:32400     # plex
        - 6080:6080       # soulseek
    restart: unless-stopped
 
 jackett:
    image: linuxserver/jackett
    network_mode: "service:transmission"
    container_name: jackett
    depends_on:
        - transmission
    env_file:
        - stack.env
    volumes:
        - /media/${USER}/Data/appdata/jackett:/config
    restart: unless-stopped
 
 radarr:
    image: linuxserver/radarr
    network_mode: "service:transmission"
    container_name: radarr
    env_file:
        - stack.env
    volumes:
        - /media/${USER}/Data/appdata/radarr:/config
        - /media/${USER}/Data/downloads:/downloads
        - /media/${USER}/Data/media:/media
    restart: unless-stopped
 
 sonarr:
    image: linuxserver/sonarr
    network_mode: "service:transmission"
    container_name: sonarr
    env_file:
        - stack.env
    volumes:
        - /media/${USER}/Data/appdata/sonarr:/config
        - /media/${USER}/Data/downloads:/downloads
        - /media/${USER}/Data/media:/media
    restart: unless-stopped

 lidarr:
    image: linuxserver/lidarr
    network_mode: "service:transmission"
    container_name: lidarr
    env_file:
        - stack.env
    volumes:
        - /media/${USER}/Data/appdata/lidarr:/config
        - /media/${USER}/Data/downloads:/downloads
        - /media/${USER}/Data/media:/media
    restart: unless-stopped

 calibre:
    image: linuxserver/calibre
    network_mode: "service:transmission"
    container_name: calibre
    env_file:
        - stack.env
    volumes:
        - /media/${USER}/Data/appdata/calibre:/config
        - /media/${USER}/Data/media/books:/books
        - /media/${USER}/Data/media/books_not_in_library:/books_add_me
    restart: unless-stopped
    
 calibre-web:
    image: linuxserver/calibre-web
    network_mode: "service:transmission"
    container_name: calibre-web
    env_file:
        - stack.env
    volumes:
       - /media/${USER}/Data/appdata/calibre-web:/config
       - /media/${USER}/Data/media/books:/books
    restart: unless-stopped    

 plex:
    image: linuxserver/plex
    network_mode: "host"
    container_name: plex
    volumes:
        - /media/${USER}/Data/appdata/plex:/config
        - /media/${USER}/Data/media/tv:/tv
        - /media/${USER}/Data/media/movies:/movies
        - /media/${USER}/Data/media/music:/music
    env_file:
        - stack.env
    restart: unless-stopped    

 soulseek:
    image: realies/soulseek
    network_mode: "service:transmission"
    container_name: soulseek
    volumes:
       - /media/${USER}/Data/appdata/soulseek:/data/.SoulseekQt
       - /media/${USER}/Data/downloads/soulseekqt:/data/Soulseek Downloads
       - /home/${USER}/.local/log/soulseek:/data/Soulseek Chat Logs
       - /media/${USER}/Data/media/music/:/data/public/music
    env_file:
       - stack.env
    restart: unless-stopped
